[tool.poetry]
name = "курсовая 4"
version = "0.1.0"
description = ""
authors = ["Ekaterina Lyamina <kkatka@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
